# Intro
print ("You walk into the abandoned Sephora.")
print ("The door slams behind you.")
print("")
print("Will you be able to find the last Refy Mascara?")
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
c1= input("Do you choose to go to the (back of the store) or stay at the (front of the store and explore)?")
if "front of the store and explore") in c1:
    print ("you walk to the mascara and eyelash curler wall")

else:
    print if ("back of the store") in c1: